#!/usr/bin/env bash
#
# Push the 21 code-review fix branches and open a PR for each.
# Generated by the 2026-06-23 review (see CODE-REVIEW-2026-06-23.md).
#
# Run this on a machine WITH GitHub access (the sandbox where the fixes were made
# has no egress, so nothing was pushed). Branches already exist locally; each is
# 1 commit off `main` (fix/gdb-mcp-session is 2), and they are file-disjoint
# (the two fix/extractor-* branches co-edit one test file but auto-merge cleanly),
# so every PR can merge independently.
#
# Usage:  bash docs/review/push-fix-prs.sh
#
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"

command -v gh >/dev/null || { echo "gh CLI not found — install it or push + open PRs manually."; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "gh not authenticated — run: gh auth login   (or: gh auth refresh -h github.com)"; exit 1; }

# Ordered most-severe first so you can review/merge the CRITICALs before the rest.
BRANCHES=(
  fix/adopt-config              # CRITICAL  arbiter adopt emits unparseable facts.incremental scalar
  fix/build-cache-key           # CRITICAL  cache key omits flags/cmd -> stale binary served as fresh
  fix/facts-overlay-staleness   # CRITICAL + HIGH  stale overlay served on the adjudication path
  fix/extractor-recursion       # HIGH      AST recursion aborts the whole snapshot
  fix/extractor-ast-scoping     # HIGH      per-file clang diagnostic scoping (silent fact loss)
  fix/engineclient-error-kind   # HIGH      indexer_unavailable no longer poisons the engine child
  fix/guard-hardening           # HIGH+MED  EvalSymlinks in guard + fence .arbiter/run/ (engines.json)
  fix/match-goal-memo           # HIGH      goal-memo replay disabled for recipes-capability matches
  fix/gdb-mcp-session           # HIGH+MED+LOW  GDB death wake + console gate + dup-token reader guard
  fix/match-durability          # HIGH(journal 0600) + MED + LOW
  fix/seat-structuredcontent    # MED       omit structuredContent instead of forwarding null
  fix/cli-status-degrade        # MED       arbiter status degrades instead of hard-failing
  fix/playbook-parser           # MED+LOW   ASCII identifiers, deterministic OrderedSteps
  fix/facts-store-durability    # MED+LOW   snapshot fsync barrier + typed errors
  fix/gtest-discovery           # MED+LOW   disabled-test accounting + non-silent discovery
  fix/engine-shared-infra       # MED+LOW   pool doc fix, fd-leak guard, dead-code
  fix/perf-mcp-validation       # MED+LOW   closed-schema enforcement + grandchild reaping
  fix/test-coverage-gaps        # MED+LOW   un-skip source-diversity + warning view-state tests
  fix/opening-templates         # MED+LOW   bind freeplay gear-up gate; "Use when" descriptions
  fix/verify-evidence-failsafe  # LOW       absent fact-completeness defaults to not-complete
  fix/docs-reconcile            # DOCS      ~22 doc/code mismatches (decisions/design/modules/proposals)
)

for b in "${BRANCHES[@]}"; do
  echo "=== $b ==="
  if ! git push -u origin "$b"; then
    echo "  !! push failed for $b — skipping its PR"
    continue
  fi
  # --fill uses each branch's commit subject/body as the PR title/body.
  gh pr create --base main --head "$b" --fill \
    || echo "  (PR for $b may already exist — check 'gh pr list')"
done

echo
echo "Done. Review open PRs with:  gh pr list --state open"
echo "Tip: the per-unit findings + 'verified sound' notes are in docs/review/CODE-REVIEW-2026-06-23.md"
